### ISSUE TITLE
Appium session times out after a long time waiting to interact with the Chrome browser

### ISSUE THREAD

**Issue by sasasa42** [appium/appium-chromedriver#128]
**The problem**
While the appium session is running on a web view on an Android device, the appium server waits for a long time, say around 10 minutes and finally closes by just logging an error message

**Environment**
Appium version (or git revision) that exhibits the issue: 1.12.1
Last Appium version that did not exhibit the issue (if applicable): Not sure, but may be way back like 1.9.0
Desktop OS/version used to run Appium: mac 10.14.4
Node.js version (unless using Appium.app|exe): 10.12.0
Npm or Yarn package manager: npm
Mobile platform/version under test: Android
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

**Details**
The below error message appears even if the element is visible and this is quite intermittent.
TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000 (Session info: chrome=73.0.3683.90)(Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.4 x86_64)

**Comment by imurchie** [comment]
Please try to turn on logging of Chromedriver (setting the `showChromedriverLog` capability to `true`) and post the _full_ server logs as a link to a [gist](https://gist.github.com).

**Comment by sasasa42** [comment]
Ok Thanks. I shall turn this ON and attach the logs when the next time it occurs. Because, right now it is quite intermittent.
