### ISSUE TITLE
Need update on npm

### ISSUE THREAD

**Issue by blemoine14** [appium/appium-chromedriver#234]
When i download appium-chromedriver using 'npm i appium-chromedriver' i get a version that goes up to chrome 93 (according to the mapping file).

I'm working on windows 10 and i'm terribly sorry if this issue is due to some sort problem with my npm or powershell version.

**Comment by KazuCocoa** [comment]
If you used appium. you can consider to give `chromedriver_autodownload` http://appium.io/docs/en/writing-running-appium/security/#insecure-features. then, appium download a proper chrome driver automatically without new modules.

**Comment by blemoine14** [comment]
I'm using appium the desktop app so launching it with parameters is not very practical but there is some progress, so thanks for that !
I still think it should be cool to sync this github and what is installed by npm.

So my issue is for another thread but just to summarize what i discovered thanks to you :
my app use samsung internet app, which is seen as chrome 92.0.4515.166 (so chromedriver 92.0.4515.107 was installed and it cannot parse capability: goog:chromeOptions  androidDeviceSerial)
When i use appium to scan my screen while chrome is open, it choose the correct version 96.0.4664.92 (so chromedriver 96.0.4664.45 was installed) but i got TimedOut when i try to switch context from my app to the web part.

**Comment by blemoine14** [comment]
(change my default browser since last update)
So it seems one cant simply scan a chrome app and try to switch to its context because it timeout, but if i try to scan my app "hosting" a chrome page and switch context to this page it works !

So the issue that make me ask to sync versions between github and npm is solved, but i still think it's a good idea.

**Comment by KazuCocoa** [comment]
Yes. I don't have any objections to create a new release:)
The package will be in the next appium release etc.
So I suggested the auto download :)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-chromedriver/commit/0c43b529b7d858129d7dc311da7c9d9b1eaccf4a
