### ISSUE TITLE
Please change the proxy requirement

### ISSUE THREAD

**Issue by rahuljawale** [appium/appium-chromedriver#25]
Currently appium-chromedriver package is designed to reach system proxy when downloading driver package. 

Please change the behaviour and consider using `npm` proxy.

**Comment by ChristophSchaal** [comment]
+1
install-npm.js should honor --proxy and --https-proxy.

**Comment by rkavalap** [comment]
Issue currently tracked under main appium repo.
 https://github.com/appium/appium/issues/7296
