### ISSUE TITLE
appium-chromedriver v2.8.1 requires Chrome browser v46+ on Android device

### ISSUE THREAD

**Issue by duylam** [appium/appium-chromedriver#30]
We're using Appium 1.4 in our system and we are exploring Appium to 1.5 before applying it. One thing we see is that the latest version of `appium-chromedriver` uses `chromedriver` v2.21 which only works with Chrome browser v46+ ([released just 6 months ago](http://googlechromereleases.blogspot.com/2015/10/chrome-for-android-update.html)). So we upgraded Chrome browser in our Android devices to v46+ in order to meet with this requirement

The thing is that if Appium 1.5 is installed to our system, we have to upgrade all Chrome browsers in our mobile devices to v46. I just wonder is using `chromedriver` v2.21 necessary for latest `appium-chromedriver` or a misconfiguration (using old version of `chromedriver` is still ok) ?

Note: if Chrome browser is device is below v46, below error message appears in console

`org.openqa.selenium.WebDriverException: unknown error: Chrome version must be >= 46.0.2490.0
(Driver info: chromedriver=2.21.371459 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Windows NT 6.1 SP1 x86) (WARNING: The server did not provide any stacktrace information)`

**Comment by FJLopezGarcia** [comment]
Same issue here

**Comment by imurchie** [comment]
You can install other versions of ChromeDriver, to support earlier versions of Chrome by using the `--chromedriver_version` option. See https://github.com/appium/appium-chromedriver#custom-chromedriver-version

**Comment by rkavalap** [comment]
you can also set chromedriver_version env variable as well.
