### ISSUE TITLE
Expose all the arguments of chromedriver. 

### ISSUE THREAD

**Issue by rkavalap** [appium/appium-chromedriver#35]
Usage: chromedriver.exe [OPTIONS]

Options
  --port=PORT                     port to listen on
  --adb-port=PORT                 adb server port
  --log-path=FILE                 write server log to file instead of stderr, increases log level to INFO
  --verbose                       log verbosely
  --version                       print the version number and exit
  --silent                        log nothing
  --url-base                      base URL path prefix for commands, e.g. wd/url
  --port-server                   address of server to contact for reserving a port
  --whitelisted-ips               comma-separated whitelist of remote IPv4 addresses which are allowed to connect to ChromeDriver

Currently only port and url-base are used. Expose --verbose and --log-path for chromedriver executable from appium server args would be nice.  

lib/chromedriver.js
lines >50

**Comment by imurchie** [comment]
Good idea!

**Comment by rkavalap** [comment]
Closing this for https://github.com/appium/appium/issues/7228
