### ISSUE TITLE
Issue in installing appium on mac through terminal window nom install appium command

### ISSUE THREAD

**Issue by Ramkumar9489** [appium/appium-chromedriver#40]
sathiyans-MacBook-Pro:~ sathiyan$ npm install appium

> appium-chromedriver@2.9.2 install /Users/sathiyan/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: connect ECONNREFUSED 74.125.68.128:80
    at new RequestError (/Users/sathiyan/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback](/Users/sathiyan/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/sathiyan/node_modules/appium/node_modules/request-promise/node_modules/request/request.js:200:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/sathiyan/node_modules/appium/node_modules/request-promise/node_modules/request/request.js:831:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
lodash@4.13.1 /Users/sathiyan
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install" "appium"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.2 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sathiyan/npm-debug.log
npm ERR! code 1

**Comment by imurchie** [comment]
Can you get to http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip ?

**Comment by Ramkumar9489** [comment]
I am able to download chromedriver_mac3
2.zip when i launch this URL 
http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip

Could you provide any solution to overcome that issur

**Comment by Ramkumar9489** [comment]
When i fire the command npm install appium i get above specifiederror

**Comment by imurchie** [comment]
What is your npm config? Are you using a proxy?

**Comment by Ramkumar9489** [comment]
Npm 3.2.1, yes we are using proxy environment

**Comment by imurchie** [comment]
Can you get to the above url through that proxy?

**Comment by idxn** [comment]
I have looked into the code and found that the request-premise library the project used will use proxy only if there is an explicit declared in the code or there is a environment system variable in the os. I have added these 2 env vars as following and it resolves the issue
http_proxy
https_proxy

**Comment by rkavalap** [comment]
Issue currently tracked under main appium repo.
https://github.com/appium/appium/issues/7296
