### ISSUE TITLE
Node install failure on version 2.9.2

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [appium/appium-chromedriver#42]
Hello!

My notice is that installing the appium-chromedriver 2.9.2 installing fails at _node install-npm.js_.
My OS is Windows_NT 6.1.7601, Node.js is 6.5.0 and npm is 3.10.7 

Thanks for resolving issue!

The log is below:
[npm-debug.zip](https://github.com/appium/appium-chromedriver/files/445061/npm-debug.zip)

It's a connection error to the http://216.58.201.208.80/ address, that I also face from any browser.

**Comment by RokaFogtaCsukaFarka** [comment]
My issue resolved, because I was behind a corporate proxy, that I set on the npm, but it didn't helped.
I had to switched to another Internet access without proxy, and then node could install the chrome driver, interestingly.

**Comment by markshao** [comment]
We should help solve the problem for some Chinese users.  The network is blocked by the GFW , so we have to use the VPN to connect to the US sever. But looks like it not works when when we try to install through `npm install -g appium` . But we could download the file directly through Curl.

**Comment by idxn** [comment]
I have looked into the code and found that the request-premise library the project used will use proxy only if there is an explicit declared in the code or there is a environment system variable in the os. I have added these 2 env vars as following and it resolves the issue
http_proxy
https_proxy

**Comment by rkavalap** [comment]
Issue currently tracked under main appium repo.
https://github.com/appium/appium/issues/7296
