### ISSUE TITLE
Error with chromedriver when installing appium

### ISSUE THREAD

**Issue by nikhiludgirkar** [appium/appium-chromedriver#45]
I am getting following error with chromedriver only when tried install of appium 1.6.0 from command line

info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com
/2.21/chromedriver_win32.zip...
RequestError: Error: socket hang up
    at new RequestError (C:\Users\nikhil.udgirkar\node_modules\appium\node_modul
es\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback](C:Usersnikhil.udgirkarnode_modules
appiumnode_modulesrequest-promiselibrp.js:60:32)
    at self.callback (C:\Users\nikhil.udgirkar\node_modules\appium\node_modules\
request\request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\nikhil.udgirkar\node_modules\appium\node
_modules\request\request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:342:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
C:\Users\nikhil.udgirkar
`-- (empty)

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nikhil.udgirka
r\package.json'
npm WARN nikhil.udgirkar No description
npm WARN nikhil.udgirkar No repository field.
npm WARN nikhil.udgirkar No README data
npm WARN nikhil.udgirkar No license field.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "appium-1.6.0.tgz"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.9.2 install script 'node install-np
m.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nikhil.udgirkar\npm-debug.log
npm ERR! code 1

Please provide solution for this

thanks

**Comment by imurchie** [comment]
What version of node and npm are you using?

**Comment by nikhiludgirkar** [comment]
node.js is v6.0.0
and npm is 3.8.6

**Comment by imurchie** [comment]
Are you behind a proxy or anything? It seems to be a network error.

**Comment by nikhiludgirkar** [comment]
No I am not using any proxy. I am still getting same error with appium 1.6

**Comment by vikramvi** [comment]
Same issue with me, we don't have any proxy in company

**Comment by rkavalap** [comment]
Issue currently tracked under main appium repo.
 https://github.com/appium/appium/issues/7296

**Comment by vikramvi** [comment]
Just to update on this, it worked from my home wi-fi. 

 In my case office modem had some bug and weird configuration which was preventing chromedriver download.
