### ISSUE TITLE
Add Support for Installing Chromedriver 2.23+ on OS X

### ISSUE THREAD

**Issue by johni1028** [appium/appium-chromedriver#47]
I tried to specify installing version 2.24 and noticed the install script is assuming 'chromedriver_mac32.zip' is the file it's looking for.

v2.23 and 2.24 use 'chromedriver_mac64.zip'

http://chromedriver.storage.googleapis.com/index.html?path=2.24/

info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip...

**Comment by duongha86** [comment]
@imurchie Could you please let me know when this fix will be available on NPM?

**Comment by imurchie** [comment]
It's available now in `appium-chromedriver@2.9.3`.

**Comment by Can-too** [comment]
@imurchie, I have used the npm install appium-chromedriver@2.9.3 however using appium command line commands have produced:

[Chromedriver] [SYSOUT] Starting ChromeDriver 2.21.371459

This is the second time that I tried to update the chrome driver but must be doing something wrong?

**Comment by imurchie** [comment]
How did you update `appium-chromedriver`? It needs to be updated within the correct part of the tree if you are doing it _ad hoc_.

**Comment by Can-too** [comment]
Using NPM from the location /usr/local/lib/node_modules/appium/node_modules/appium-android-driver 
I ran the npm command: 

`npm install appium@2.9.4 `

Tested and all is working fine....
