### ISSUE TITLE
The Added Support for Installing Chromedriver 2.23+ on OS X

### ISSUE THREAD

**Issue by Can-too** [appium/appium-chromedriver#52]
I am using version 1.5.3 of Appium and attempting to upgrade my ChromeDriver to 2.9.3 to overcome the issues related to version 6.0.1 on Android Devices. I'm using a MAC MINI using El Capitan. Appium and the tests were working fine until the Android Phones were updated. I found the previously resolved issue with the same title and created a comment on it and opend this issue. I did it this way because I wasn't certain if the issue I'm having relates directley to the packaging of the Chromedriver in the previous issue OR to the nmp update that may not working as expected...
  
@imurchie, I have used the npm to install appium-chromedriver@2.9.3 however when starting Appium 1.5.3 I see in the log the entry:

[Chromedriver] [SYSOUT] Starting ChromeDriver 2.21.371459

This is the second time that I tried to update the chrome driver (now showing version 2.9.4) which seems to be installed but Appium is either producing this erroneous message or not picking up the latest installed chromedriver. Maybe its not an error and I'm just doing something wrong?

**Comment by rkavalap** [comment]
If you just to want to get the latest version of chromedriver try installing 
npm install appium@beta -g
I believe appium v1.5.3 and appium v1.6 still default v2.21 of chromedriver. The updates to the latest will only reflect to appium v1.6.1. 
IMO this is not an appium issue.

**Comment by Can-too** [comment]
@rkavalap I think you have prematurely closed this issue. I have a working test bed of mobile devices and do not want to update the Appium version 1.5.3 in use and replace it with a beta version. I would like to adopt the newest version of the Chrome Driver into this version of Appium to minimise the risk of breaking the productive tests running. 

The previous issue with the same title suggested this was possible and wanted to confirm why the upgrade was not working as described previously. Either I'm making a mistake or there is an issue.... Please see Add Support for Installing Chromedriver 2.23+ on OS X **#47**

**Comment by rkavalap** [comment]
@Can-too  If you believe this is an issue in appium-chromedriver package can you open an issue 
main appium repo with the relevant information for it to be investigated

**Comment by rkavalap** [comment]
This is what i am seeing in my console on my mac when installing the latest version of appium-chromedriver. 
<img width="1432" alt="chromedriver_install" src="https://cloud.githubusercontent.com/assets/80310/20255409/250c8b24-a9f1-11e6-968d-c65ce285dc3f.png">

**Comment by Can-too** [comment]
@rkavalap many thanks for reconsidering this issue: To answer your first question How are you installing..? I'm simply using the command at the tom of the following:

`

rawpscm110:~ tabsvrad$ npm install -g appium-chromedriver@2.9.3

> appium-chromedriver@2.9.3 install /usr/local/lib/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.25' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip...
info Chromedriver Install Writing binary content to /var/folders/n6/bych3_bs2fs5wnt0lvj2ld980000gn/T/20161014-2923-zc4z94.2pio58w7b9/chromedriver_mac64.zip...
info Chromedriver Install Extracting /var/folders/n6/bych3_bs2fs5wnt0lvj2ld980000gn/T/20161014-2923-zc4z94.2pio58w7b9/chromedriver_mac64.zip to /var/folders/n6/bych3_bs2fs5wnt0lvj2ld980000gn/T/20161014-2923-zc4z94.2pio58w7b9/chromedriver_mac64
info Chromedriver Install Creating /usr/local/lib/node_modules/appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /var/folders/n6/bych3_bs2fs5wnt0lvj2ld980000gn/T/20161014-2923-zc4z94.2pio58w7b9/chromedriver_mac64/chromedriver...
info Chromedriver Install Writing to /usr/local/lib/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /usr/local/lib/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place
/usr/local/lib
└─┬ appium-chromedriver@2.9.3 
  ├── adm-zip@0.4.7 
  ├─┬ appium-base-driver@2.0.25 
  │ ├─┬ body-parser@1.15.2 
  │ │ ├── bytes@2.4.0 
  │ │ ├── content-type@1.0.2 
  │ │ ├── debug@2.2.0 
  │ │ ├── depd@1.1.0 
  │ │ ├─┬ http-errors@1.5.0 
  │ │ │ ├── inherits@2.0.1 
  │ │ │ ├── setprototypeof@1.0.1 
  │ │ │ └── statuses@1.3.1 
  │ │ ├── iconv-lite@0.4.13 
  │ │ ├─┬ on-finished@2.3.0 
  │ │ │ └── ee-first@1.1.1 
  │ │ ├── qs@6.2.0 
  │ │ ├─┬ raw-body@2.1.7 
  │ │ │ └── unpipe@1.0.0 
  │ │ └─┬ type-is@1.6.13 
  │ │   └── media-typer@0.3.0 
  │ ├── colors@1.1.2 
  │ ├── es6-error@2.1.1 
  │ ├─┬ express@4.14.0 
  │ │ ├─┬ accepts@1.3.3 
  │ │ │ └── negotiator@0.6.1 
  │ │ ├── array-flatten@1.1.1 
  │ │ ├── content-disposition@0.5.1 
  │ │ ├── cookie@0.3.1 
  │ │ ├── cookie-signature@1.0.6 
  │ │ ├── encodeurl@1.0.1 
  │ │ ├── escape-html@1.0.3 
  │ │ ├── etag@1.7.0 
  │ │ ├── finalhandler@0.5.0 
  │ │ ├── fresh@0.3.0 
  │ │ ├── merge-descriptors@1.0.1 
  │ │ ├── methods@1.1.2 
  │ │ ├── parseurl@1.3.1 
  │ │ ├── path-to-regexp@0.1.7 
  │ │ ├─┬ proxy-addr@1.1.2 
  │ │ │ ├── forwarded@0.1.0 
  │ │ │ └── ipaddr.js@1.1.1 
  │ │ ├── range-parser@1.2.0 
  │ │ ├─┬ send@0.14.1 
  │ │ │ ├── destroy@1.0.4 
  │ │ │ └── mime@1.3.4 
  │ │ ├── serve-static@1.11.1 
  │ │ ├── utils-merge@1.0.0 
  │ │ └── vary@1.1.0 
  │ ├── lodash@4.16.6 
  │ ├── method-override@2.3.6 
  │ ├─┬ morgan@1.7.0 
  │ │ ├── basic-auth@1.0.4 
  │ │ └── on-headers@1.0.1 
  │ ├─┬ request-promise@4.1.1 
  │ │ ├── bluebird@3.4.6 
  │ │ ├─┬ request-promise-core@1.1.1 
  │ │ │ └── lodash@4.16.6 
  │ │ └── stealthy-require@1.0.0 
  │ ├─┬ serve-favicon@2.3.0 
  │ │ └── ms@0.7.1 
  │ ├─┬ source-map-support@0.4.6 
  │ │ └── source-map@0.5.6 
  │ ├── uuid-js@0.7.5 
  │ └── validate.js@0.9.0 
  ├─┬ appium-logger@2.1.0 
  │ └─┬ npmlog@2.0.4 
  │   ├── ansi@0.3.1 
  │   ├─┬ are-we-there-yet@1.1.2 
  │   │ ├── delegates@1.0.0 
  │   │ └─┬ readable-stream@2.2.1 
  │   │   ├── buffer-shims@1.0.0 
  │   │   ├── core-util-is@1.0.2 
  │   │   ├── isarray@1.0.0 
  │   │   ├── process-nextick-args@1.0.7 
  │   │   └── string_decoder@0.10.31 
  │   └─┬ gauge@1.2.7 
  │     ├── has-unicode@2.0.1 
  │     ├── lodash.pad@4.5.1 
  │     ├── lodash.padend@4.6.1 
  │     └── lodash.padstart@4.6.1 
  ├─┬ appium-support@2.3.5 
  │ ├─┬ bplist-creator@0.0.6 
  │ │ └── stream-buffers@2.2.0 
  │ ├─┬ bplist-parser@0.1.1 
  │ │ └── big-integer@1.6.17 
  │ ├─┬ glob@6.0.4 
  │ │ ├─┬ inflight@1.0.6 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ minimatch@3.0.3 
  │ │ │ └─┬ brace-expansion@1.1.6 
  │ │ │   ├── balanced-match@0.4.2 
  │ │ │   └── concat-map@0.0.1 
  │ │ ├── once@1.4.0 
  │ │ └── path-is-absolute@1.0.1 
  │ ├── lodash@4.16.6 
  │ ├── md5-file@2.0.7 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ mv@2.1.1 
  │ │ └── rimraf@2.4.5 
  │ ├── ncp@2.0.0 
  │ ├─┬ plist@1.2.0 
  │ │ ├── base64-js@0.0.8 
  │ │ ├── util-deprecate@1.0.2 
  │ │ ├── xmlbuilder@4.0.0 
  │ │ └── xmldom@0.1.22 
  │ ├─┬ rimraf@2.5.4 
  │ │ └─┬ glob@7.1.1 
  │ │   └── fs.realpath@1.0.0 
  │ └─┬ which@1.2.12 
  │   └── isexe@1.1.2 
  ├─┬ asyncbox@2.3.1 
  │ ├─┬ babel-runtime@5.5.5 
  │ │ └── core-js@0.9.18 
  │ ├─┬ chai@3.5.0 
  │ │ ├── assertion-error@1.0.2 
  │ │ ├─┬ deep-eql@0.1.3 
  │ │ │ └── type-detect@0.1.1 
  │ │ └── type-detect@1.0.0 
  │ ├── chai-as-promised@5.3.0 
  │ └─┬ es6-mapify@1.0.0 
  │   └─┬ traceur@0.0.111 
  │     ├── glob@5.0.15 
  │     ├── rsvp@3.3.3 
  │     ├── semver@4.3.6 
  │     └── source-map-support@0.2.10 
  ├─┬ babel-runtime@5.8.24 
  │ └── core-js@1.2.7 
  ├── bluebird@2.11.0 
  ├─┬ continuation-local-storage@3.2.0 
  │ ├─┬ async-listener@0.6.3 
  │ │ └── shimmer@1.0.0 
  │ └── emitter-listener@1.0.1 
  ├── is-os@1.0.0 
  ├── lodash@3.10.1 
  ├─┬ request@2.78.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.5.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.2 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.15.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@4.0.0 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.14.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.12 
  │ │ └── mime-db@1.24.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.0 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ └── tunnel-agent@0.4.3 
  ├─┬ request-promise@1.0.2 
  │ └─┬ cls-bluebird@1.1.3 
  │   ├── is-bluebird@1.0.2 
  │   └── shimmer@1.1.0 
  ├─┬ source-map-support@0.3.3 
  │ └─┬ source-map@0.1.32 
  │   └── amdefine@1.0.1 
  ├─┬ teen_process@1.6.2 
  │ ├─┬ shell-quote@1.6.1 
  │ │ ├── array-filter@0.0.1 
  │ │ ├── array-map@0.0.0 
  │ │ ├── array-reduce@0.0.0 
  │ │ └── jsonify@0.0.0 
  │ └── source-map-support@0.2.10 
  └── through@2.3.8 

rawpscm110:~ tabsvrad$ 
`

Which all seems good no?

**Comment by rkavalap** [comment]
@Can-too  I believe you are executing the command from your home directory or else where. 
appium-chromedriver is getting installed under /usr/local/lib/node_modules/appium-chromedriver.
But when appium itself is executed, it launches from the appium dependent packages and the flow in this case is launches appium-android-driver which internally launches appium-chromedriver
/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver

So try executing 
npm install appium@2.9.4 
from /usr/local/lib/node_modules/appium/node_modules/appium-android-driver
and execute your test. That should fix your issue.

**Comment by Can-too** [comment]
@rkavalap Sir, You are a star...!  You are indeed correct that solved my problem completely!!! And you completely exposed my ignorance,.... MANY THANKS!!!!. This issue be closed

**Comment by rkavalap** [comment]
You are welcome.
