### ISSUE TITLE
Error with chromedriver when installing appium1.6.0

### ISSUE THREAD

**Issue by 1214503056** [appium/appium-chromedriver#53]
I am getting following error with chromedriver only when tried install of appium 1.6.0 from command line

localhost:~ yongche$ npm install -g appium

> appium-chromedriver@2.9.2 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:2130) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: read ECONNRESET
    at new RequestError (/Users/yongche/Downloads/Appium/appium-1.6.0/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/yongche/Downloads/Appium/appium-1.6.0/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/yongche/Downloads/Appium/appium-1.6.0/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/yongche/Downloads/Appium/appium-1.6.0/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
lodash@3.10.1 node_modules/appium/node_modules/rcloader/node_modules/lodash -> node_modules/appium/node_modules/appium-android-driver/node_modules/lodash
lodash@3.10.1 node_modules/appium/node_modules/jsdoctypeparser/node_modules/lodash -> node_modules/appium/node_modules/appium-chromedriver/node_modules/lodash
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.2 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yongche/npm-debug.log
npm ERR! code 1

    Please provide solution for this

   thanks

**Comment by imurchie** [comment]
Are you able to download http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip manually?

**Comment by 1214503056** [comment]
I can.

**Comment by 1214503056** [comment]
I can.
Help me，please.
Thanks!

**Comment by 1214503056** [comment]
I am using a proxy,or not using a proxy,the error is the same.

**Comment by imurchie** [comment]
What version of Mac are you using?

Also: does Appium 1.6.1-beta work? If you try `npm install -g appium@beta`?

**Comment by 1214503056** [comment]
MacBook Pro OS X EI Capitan  10.11.5
Try npm install -g appium@beta,looking below
Last login: Fri Nov 18 14:00:12 on console
localhost:~ yongche$ npm install -g appium@beta
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN update-linked node_modules/appium needs updating to 1.6.1-beta from 1.6.0 but we can't, as it's a symlink
localhost:~ yongche$

**Comment by 1214503056** [comment]
localhost:~ yongche$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (8.0) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/appium
  /usr/local/lib/node_modules/app-inspector/node_modules/.bin/java-home
  /usr/local/lib/node_modules/app-inspector/node_modules/.bin/win-spawn
localhost:~ yongche$

**Comment by imurchie** [comment]
This seems like something is mis-configured on your machine. Can you remove the symlink and try the install?

**Comment by 1214503056** [comment]
How remove the symlink,please?

**Comment by 1214503056** [comment]
When Officially released the Appium1.6.0.dmg？

It is ok that removing the broken symlinks with brew prune.
 Then,install with npm install -g appium@beta ,i am getting following error,help me! 

localhost:~ yongche$ brew prune

localhost:~ yongche$ npm install -g appium@beta
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN update-linked node_modules/appium needs updating to 1.6.1-beta from 1.6.0 but we can't, as it's a symlink

**Comment by imurchie** [comment]
Can you uninstall the old Appium first? This is some weird npm problem.

**Comment by 1214503056** [comment]
@imurchie Delete the file "Appium" and "Appium-doctor" , than appium is installed Victory!

Thank you very much! 

See below,

localhost:~ yongche$ appium
[Appium] Welcome to Appium v1.6.1-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by rkavalap** [comment]
Closing issue
